name: Run Playwright tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install Angular program dependencies, Angular global CLI + ng build
        run: cd frontend && npm i -g @angular/cli && npm i && ng build -c="development"

      - name: Build test code and install playwright test browser
        run: cd PlaywrightTests && dotnet build && pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps

      - name: Build and run Web API + getting process ID for shutting down later
        run: cd api && dotnet run & echo "API_PID=$!"

      - name: Build and run Frontend Angular + getting process ID for shutting down later
        run: cd frontend && ng serve --open & echo "API_PID=$!"b
      
      - name: Run tests once API is running (sleep interval set to 60 seconds)
        run: cd PlaywrightTests && sleep 60 && dotnet test  
      
      - name: Shutdown Web API once the tests are done running
        run: kill $API_PID  
